### ISSUE TITLE
久しぶり〜

### ISSUE THREAD

**Issue by mi-wada** [seiyawati/c-lang-study#1]
ナビタイムのインターンで一緒だった和田です✋ 

C何に使うの？

**Comment by seiyawati** [comment]
> ナビタイムのインターンで一緒だった和田です✋
> 
> C何に使うの？

お久しぶりです！

大学の研究でC/C++書く機会があって勉強はじめました！

**Comment by mi-wada** [comment]
なるほど、がんばって 👍
